baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'risotto'
title = 'Portfolio'
author = ''

sectionPagesMenu = "main"

[params]
noindex = false

[params.about]
title = ""
description = ""

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
